[package]
name = "encre-css"
version = "0.1.0"
description = "A TailwindCSS-compatible CSS generation library written in Rust"
authors = ["nifou <nifou@mailfence.com>"]
license = "MIT"
edition = "2021"

[dependencies]
toml = "0.5.9"
serde = "1.0.137"
serde_derive = "1.0.137"
color-name = "1.1.0"
lazy_static = "1.4.0"
regex = "1.5.5"
rayon = "1.5.2"
wax = "0.4.0"
thiserror = "1.0.31"

[dev-dependencies]
pretty_assertions = "1.2.1"
