[package]
name = "encre-css"
version = "0.13.0"
description = "A TailwindCSS-compatible utility-first CSS generation library written in Rust"
authors = ["nifou <nifou@mailfence.com>"]
license = "MIT"
edition = "2021"
repository = "https://gitlab.com/encre-org/encre-css.git"
documentation = "https://docs.rs/encre-css"
readme.workspace = true
keywords = ["tailwind", "css", "compiler"]
categories = ["web-programming"]

[[bench]]
name = "benchmark"
harness = false

[dependencies]
toml = "0.8.8"
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.34"
phf = { version = "0.11.1", features = ["macros"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
criterion = { version = "0.5.1", features = ["html_reports"] }
