[package]
name = "encre-css"
version = "0.4.0"
description = "A TailwindCSS-compatible CSS generation library written in Rust"
authors = ["nifou <nifou@mailfence.com>"]
license = "MIT"
edition = "2021"
repository = "https://gitlab.com/encre-css/encre-css"
documentation = "https://encre-css.gitlab.io/encre-css/encre_css.git"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
toml = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
rayon = { version = "1.5.2", optional = true }
thiserror = "1.0.31"

[dev-dependencies]
pretty_assertions = "1.2.1"
criterion = { version = "0.3", features = ["html_reports"] }
