[package]
name = "tailwind-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
globwalk = "0.8.1"
regex = "1.5.5"
color-name = "1.0.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
