[package]
name = "encre-css-cli"
version = "0.8.0"
description = "A TailwindCSS-compatible utility-first CSS generation library written in Rust"
authors = ["nifou <nifou@mailfence.com>"]
license = "MIT"
edition = "2021"

[[bin]]
name = "encrecss"
path = "src/main.rs"

[dependencies]
encre-css = { path = "../encre-css" }
clap = { version = "4.0.18", features = ["derive"] }
notify-debouncer-mini = "0.2.1"
rand = "0.8.5"
wax = "0.5.0"
color-eyre = "0.6.1"
toml = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
