[package]
name = "encre-css-cli"
version = "0.1.0"
description = "A TailwindCSS-compatible CSS generation library written in Rust"
authors = ["nifou <nifou@mailfence.com>"]
license = "MIT"
edition = "2021"

[dependencies]
encre-css = { path = "../encre-css" }
clap = { version = "3.1.17", features = ["derive"] }
