use super::Plugin;

#[derive(Debug)]
pub struct FilterPlugin;

impl Plugin for FilterPlugin {
    fn namespace(&self) -> String {
        "".to_string()
    }

    fn get_css_for_modifier(&self, modifier: &str) -> Option<String> {
        match modifier {
            "filter" => Some("".to_string()),
            "filter-none" => Some("".to_string()),
            "blur-0" => Some("".to_string()),
            "blur-sm" => Some("".to_string()),
            "blur" => Some("".to_string()),
            "blur-md" => Some("".to_string()),
            "blur-lg" => Some("".to_string()),
            "blur-xl" => Some("".to_string()),
            "blur-2xl" => Some("".to_string()),
            "blur-3xl" => Some("".to_string()),
            "brightness-0" => Some("".to_string()),
            "brightness-50" => Some("".to_string()),
            "brightness-75" => Some("".to_string()),
            "brightness-90" => Some("".to_string()),
            "brightness-95" => Some("".to_string()),
            "brightness-100" => Some("".to_string()),
            "brightness-105" => Some("".to_string()),
            "brightness-110" => Some("".to_string()),
            "brightness-125" => Some("".to_string()),
            "brightness-150" => Some("".to_string()),
            "brightness-200" => Some("".to_string()),
            "contrast-0" => Some("".to_string()),
            "contrast-50" => Some("".to_string()),
            "contrast-75" => Some("".to_string()),
            "contrast-100" => Some("".to_string()),
            "contrast-125" => Some("".to_string()),
            "contrast-150" => Some("".to_string()),
            "contrast-200" => Some("".to_string()),
            "drop-shadow-sm" => Some("drop-shadow: drop-shadow(0 1px 1px rgba(0,0,0,0.05));".to_string()),
            "drop-shadow" => Some("drop-shadow: drop-shadow(0 1px 2px rgba(0, 0, 0, 0.1)) drop-shadow(0 1px 1px rgba(0, 0, 0, 0.06));".to_string()),
            "drop-shadow-md" => Some("drop-shadow: drop-shadow(0 4px 3px rgba(0, 0, 0, 0.07)) drop-shadow(0 2px 2px rgba(0, 0, 0, 0.06));".to_string()),
            "drop-shadow-lg" => Some("drop-shadow: drop-shadow(0 10px 8px rgba(0, 0, 0, 0.04)) drop-shadow(0 4px 3px rgba(0, 0, 0, 0.1));".to_string()),
            "drop-shadow-xl" => Some("drop-shadow: drop-shadow(0 20px 13px rgba(0, 0, 0, 0.03)) drop-shadow(0 8px 5px rgba(0, 0, 0, 0.08));".to_string()),
            "drop-shadow-2xl" => Some("drop-shadow: drop-shadow: drop-shadow(0 25px 25px rgba(0, 0, 0, 0.15));".to_string()),
            "drop-shadow-none" => Some("drop-shadow: drop-shadow: drop-shadow(0 0 #0000);".to_string()),
            "grayscale-0" => Some("--tw-grayscale: grayscale(0); filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);".to_string()),
            "grayscale" => Some("--tw-grayscale: grayscale(100%); filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);".to_string()),
            "-hue-rotate-180" => Some("hue-rotate: hue-rotate(-180deg);".to_string()),
            "-hue-rotate-90" => Some("hue-rotate: hue-rotate(-90deg);".to_string()),
            "-hue-rotate-60" => Some("hue-rotate: hue-rotate(-60deg);".to_string()),
            "-hue-rotate-30" => Some("hue-rotate: hue-rotate(-30deg);".to_string()),
            "-hue-rotate-15" => Some("hue-rotate: hue-rotate(-15deg);".to_string()),
            "hue-rotate-0" => Some("hue-rotate: hue-rotate(0deg);".to_string()),
            "hue-rotate-15" => Some("hue-rotate: hue-rotate(15deg);".to_string()),
            "hue-rotate-30" => Some("hue-rotate: hue-rotate(30deg);".to_string()),
            "hue-rotate-60" => Some("hue-rotate: hue-rotate(60deg);".to_string()),
            "hue-rotate-90" => Some("hue-rotate: hue-rotate(90deg);".to_string()),
            "hue-rotate-180" => Some("hue-rotate: hue-rotate(180deg);".to_string()),
            "invert-0" => Some("invert: invert(0);".to_string()),
            "invert" => Some("invert: invert(1);".to_string()),
            "saturate-0" => Some("".to_string()),
            "saturate-50" => Some("".to_string()),
            "saturate-100" => Some("".to_string()),
            "saturate-150" => Some("".to_string()),
            "saturate-200" => Some("".to_string()),
            "sepia-0" => Some("".to_string()),
            "sepia" => Some("".to_string()),
            "backdrop-filter" => Some("".to_string()),
            "backdrop-filter-none" => Some("".to_string()),
            "backdrop-blur-0" => Some("".to_string()),
            "backdrop-blur-sm" => Some("".to_string()),
            "backdrop-blur" => Some("".to_string()),
            "backdrop-blur-md" => Some("".to_string()),
            "backdrop-blur-lg" => Some("".to_string()),
            "backdrop-blur-xl" => Some("".to_string()),
            "backdrop-blur-2xl" => Some("".to_string()),
            "backdrop-blur-3xl" => Some("".to_string()),
            "backdrop-brightness-0" => Some("".to_string()),
            "backdrop-brightness-sm" => Some("".to_string()),
            "backdrop-brightness" => Some("".to_string()),
            "backdrop-brightness-md" => Some("".to_string()),
            "backdrop-brightness-lg" => Some("".to_string()),
            "backdrop-brightness-xl" => Some("".to_string()),
            "backdrop-brightness-2xl" => Some("".to_string()),
            "backdrop-brightness-3xl" => Some("".to_string()),
            "backdrop-contrast-0" => Some("".to_string()),
            "backdrop-contrast-50" => Some("".to_string()),
            "backdrop-contrast-75" => Some("".to_string()),
            "backdrop-contrast-100" => Some("".to_string()),
            "backdrop-contrast-125" => Some("".to_string()),
            "backdrop-contrast-150" => Some("".to_string()),
            "backdrop-contrast-200" => Some("".to_string()),
            "backdrop-grayscale-0" => Some("".to_string()),
            "backdrop-grayscale" => Some("".to_string()),
            "-backdrop-hue-rotate-180" => Some("".to_string()),
            "-backdrop-hue-rotate-90" => Some("".to_string()),
            "-backdrop-hue-rotate-60" => Some("".to_string()),
            "-backdrop-hue-rotate-30" => Some("".to_string()),
            "-backdrop-hue-rotate-15" => Some("".to_string()),
            "backdrop-hue-rotate-0" => Some("".to_string()),
            "backdrop-hue-rotate-15" => Some("".to_string()),
            "backdrop-hue-rotate-30" => Some("".to_string()),
            "backdrop-hue-rotate-60" => Some("".to_string()),
            "backdrop-hue-rotate-90" => Some("".to_string()),
            "backdrop-hue-rotate-180" => Some("".to_string()),
            "backdrop-invert-0" => Some("".to_string()),
            "backdrop-invert" => Some("".to_string()),
            "backdrop-opacity-0" => Some("".to_string()),
            "backdrop-opacity-5" => Some("".to_string()),
            "backdrop-opacity-10" => Some("".to_string()),
            "backdrop-opacity-20" => Some("".to_string()),
            "backdrop-opacity-25" => Some("".to_string()),
            "backdrop-opacity-30" => Some("".to_string()),
            "backdrop-opacity-40" => Some("".to_string()),
            "backdrop-opacity-50" => Some("".to_string()),
            "backdrop-opacity-60" => Some("".to_string()),
            "backdrop-opacity-70" => Some("".to_string()),
            "backdrop-opacity-75" => Some("".to_string()),
            "backdrop-opacity-80" => Some("".to_string()),
            "backdrop-opacity-90" => Some("".to_string()),
            "backdrop-opacity-95" => Some("".to_string()),
            "backdrop-opacity-100" => Some("".to_string()),
            "backdrop-saturate-0" => Some("".to_string()),
            "backdrop-saturate-50" => Some("".to_string()),
            "backdrop-saturate-100" => Some("".to_string()),
            "backdrop-saturate-150" => Some("".to_string()),
            "backdrop-saturate-200" => Some("".to_string()),
            "backdrop-sepia-0" => Some("".to_string()),
            "backdrop-sepia" => Some("".to_string()),
            _ => None,
        }
    }
}
